In [6]:
import numpy as np

In [9]:
# 第一題:將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
array = array1.reshape(5, 6, order="F")
print(array)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [10]:
# 第二題:呈上題的array，找出被6除餘1的數的索引
remainder = array % 6
np.where(remainder==1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))