In [2]:
import numpy as np

In [24]:
# 第一題:將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
np.savez('D06example.npz', arr1=array1, arr2=array2)

In [30]:
# 第二題:讀取剛剛的npz檔，加入下列array一起存成新的npz檔
new_array = np.array([1,2,3,4,5])

D06npzfile = np.load('D06example.npz')
print(D06npzfile['arr1'])
print(D06npzfile['arr2'])
np.savez('new_D06example.npz', arr1=D06npzfile['arr1'], arr2=D06npzfile['arr2'], arr3=new_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [31]:
file = np.load('new_D06example.npz')
print(file['arr1'])
print(file['arr2'])
print(file['arr3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[1 2 3 4 5]
