In [1]:
import numpy as np

In [8]:
# 第一題: 運用下列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
inv_array1 = np.linalg.inv(array1)
print("inv_array1:", inv_array1, sep="\n")
id_array = np.dot(array1, inv_array1)
print("id_array:", id_array, sep="\n")

inv_array1:
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
id_array:
[[1. 0.]
 [0. 1.]]


In [10]:
# 第二題: 運用上列array計算特徵值、特徵向量?
eigenvalue, eigenvector = np.linalg.eig(array1)
print("eigenvalue:", eigenvalue, sep="\n")
print("eigenvector:", eigenvector, sep="\n")

eigenvalue:
[13.  2.]
eigenvector:
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [16]:
# 第三題: 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)

In [18]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [19]:
s

array([13.94721714,  1.86417116])

In [20]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])